### ISSUE TITLE
Could install the plugin

### ISSUE THREAD

**Issue by Devoter** [m0dch3n/vue-cli-plugin-cordova#132]
I just running `vue add cordova`, sets the app id and name.

> 🚀  Invoking generator for vue-cli-plugin-cordova...
⠋  Running completion hooks...App id contains a reserved word, or is not a valid identifier.
⚓  Running completion hooks...
 ERROR  Error: ENOENT: no such file or directory, open '...<project-root>/src-cordova/www/.gitignore'
Error: ENOENT: no such file or directory, open '...<project-root>/src-cordova/www/.gitignore'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at ...<project-root>/node_modules/vue-cli-plugin-cordova/generator.js:113:8
    at runGenerator (/usr/lib/node_modules/@vue/cli/lib/invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async invoke (/usr/lib/node_modules/@vue/cli/lib/invoke.js:92:3)

**Comment by webcodepl** [comment]
> Running completion hooks...App id contains a reserved word, or is not a valid identifier.

Change app id, probably you used reserved chars like e.g. '-'
