### ISSUE TITLE
Failed to add plugin - please help. Thanks!

### ISSUE THREAD

**Issue by jonathanw2004** [m0dch3n/vue-cli-plugin-cordova#52]
>vue add cordova

📦  Installing vue-cli-plugin-cordova...

+ vue-cli-plugin-cordova@2.1.0
removed 1 package, updated 2 packages and audited 32965 packages in 12.061s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-cordova

 ERROR  SyntaxError: Unexpected string
..\node_modules\vue-cli-plugin-cordova\generator.js:29
      'cordova-serve-osx': 'vue-cli-service cordova-serve-osx',
      ^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at exports.loadModule (..\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\lib\module.js:51:12)

**Comment by inyourhands** [comment]
Same here~
